problem 1

task1

In [ ]:
import numpy as np
a = np.empty((2,3))
print(a)

[[4.90725749e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


task2

In [ ]:
import numpy as np
a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


task3

In [ ]:
import numpy as np
a = (2,2)
b = 3
answer = np.full(a,b)
print(answer)

[[3 3]
 [3 3]]


task4

In [ ]:
import numpy as np
a = np.array([[4,4],[3,8]])
b = np.zeros_like(a)
print(b)

[[0 0]
 [0 0]]


task5

In [ ]:
import numpy as np
a = np.array([[4,4],[3,8]])
b = np.ones_like(a)
print(b)

[[1 1]
 [1 1]]


Task6

In [ ]:
import numpy as np
list1 = [1,2,3,4]
array1 = np.array(list1)
print(array1)

[1 2 3 4]


problem 2

task1

In [ ]:
import numpy as np
array1 = np.arange(10,49)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


task2

In [ ]:
import numpy as np
array1 = np.arange(0,9)
answer = array1.reshape(3,3)
print(answer)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


task3

In [ ]:
import numpy as np
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


task4

In [ ]:
import numpy as np
array = np.random.rand(10)
mean = array.mean()
print(mean)

0.5560495846043758


task5

In [ ]:
import numpy as np
array = np.random.rand(100)
answer = array.reshape(10,10)
max = max(array)
min = min(array)
print(answer)
print(f"the maximum value is: {max}")
print(f"the minimum value is: {min}")


[[0.00698529 0.96543924 0.93840333 0.71554852 0.31184523 0.51336037
  0.99588523 0.93671791 0.90351625 0.27880997]
 [0.31502148 0.40109373 0.57819793 0.32850109 0.54401264 0.37512767
  0.96390853 0.67158003 0.31016566 0.01126168]
 [0.53988295 0.74921668 0.9666823  0.68333823 0.04199431 0.54709625
  0.93292219 0.9562866  0.63803295 0.3798247 ]
 [0.0661085  0.08069648 0.80959271 0.18652526 0.81963005 0.73721067
  0.09058478 0.0637725  0.68582223 0.45911184]
 [0.45361026 0.11108483 0.86027122 0.14085131 0.04429889 0.6857483
  0.08629745 0.53896246 0.07809653 0.73817188]
 [0.53403756 0.40790844 0.20632272 0.26256947 0.11840172 0.24669531
  0.40938816 0.61585162 0.10009144 0.12462307]
 [0.64254739 0.4024508  0.23367214 0.26141567 0.75128727 0.3142131
  0.75375129 0.88535176 0.21479144 0.78104086]
 [0.77170098 0.12861718 0.74192045 0.80076898 0.77671271 0.50972139
  0.24905739 0.82163871 0.26749186 0.20534836]
 [0.18087461 0.09478442 0.66224824 0.01472211 0.74475813 0.35182782
  0.37580926 0

Task6

In [ ]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


task7

In [2]:
import numpy as np

array = [1,2,0,0,4,0]
array = np.array(array)
reversed_array = np.flip(array)
print(reversed_array)

[0 4 0 0 2 1]


In [5]:
import numpy as np

array= np.zeros((5, 5))

for i in range(5):
    for j in range(5):
        if i == 0 or i == 4 or j == 0 or j == 4:
            array[i, j] = 1

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
import numpy as np

checkerboard = np.zeros((8, 8))

for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            checkerboard[i, j] = 1
        else:
            checkerboard[i, j] = 0

print(checkerboard)


[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


problem 3


In [8]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum = x + y
print(sum)

[[ 6  8]
 [10 13]]


In [9]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sub = x-y
print(sub)

[[-4 -4]
 [-4 -3]]


In [10]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square = x*x
print(square)

[[ 1  4]
 [ 9 25]]


In [11]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
product = np.dot(v,w)
product1 = np.dot(x,v)
product2 = np.dot(x,y)
print(product)
print(product1)
print(product2)

219
[29 77]
[[19 22]
 [50 58]]


In [13]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
concatanation = np.concatenate((x,y),axis=1)
print(concatanation)
concatanation2 = np.concatenate((v, w), axis = 0)
print(concatanation2)

[[1 2 5 6]
 [3 5 7 8]]
[ 9 10 11 12]


In [14]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
concatanation = np.concatenate((x,v),axis=1)
print(concatanation)
#we get an error because the array doesnt have the same no of dimensions while x has 2 dimensions v has only 1 dimensions

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

problem 4

In [20]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
inverse = np.linalg.inv(A)
mul = np.dot(A ,inverse)
print(mul)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [21]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
product1 = np.dot(A,B)
product2 = np.dot(B,A)
comparison = product1 == product2
print(comparison)

[[False False]
 [False False]]


In [23]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
product = np.dot(A,B)
transpose = np.transpose(product)
transpose1 = np.transpose(A)
transpose2 = np.transpose(B)
product1 = np.dot(transpose2,transpose1)
comparison = transpose == product1
print(comparison)

[[ True  True]
 [ True  True]]


In [27]:
import numpy as np
A = np.array([[2, -3, 1],[1, -1, 2],[3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(f"the value of x y and z is: {X}")


the value of x y and z is: [ 2.  1. -2.]
